<?xml version="1.0"?>
<robot name="test_joint" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="base_width" value="0.08" /> 
  <xacro:property name="base_height" value="0.06" />
  <xacro:property name="base_depth" value="0.03" />
  <xacro:property name="gripper_width" value="0.02" />
  <xacro:property name="gripper_height" value="0.1" />

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find dynamixel_ros_control)/tests/materials.xacro" />

  <!-- Base Link -->
  <link name="link_base">
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${base_width} ${base_depth} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${base_width} ${base_depth} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link_base"/>
    <child link="link1"/>
    <origin xyz="${base_width/2} 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.35" upper="${PI/2}" effort="1" velocity="1" />
  </joint>

  <!-- Middle Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${gripper_height/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${gripper_width} ${gripper_width} ${gripper_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${gripper_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_width} ${gripper_width} ${gripper_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
