scan_range: 20

# which dynamixel ids to control, should be the same order as hardware_interface.joints
dynamixel_ids:
- 1

# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.05

# Settings for ros_control hardware interface
hardware_interface:
  joints:
  # - joint1
  - joint2
  sim_control_mode: 0 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
joint1_position_controller:
   type: position_controllers/JointPositionController
   joint: joint1

joint1_position_controller:
   type: position_controllers/JointPositionController
   joint: joint2

# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints
joint_position_controller:
   type: position_controllers/JointGroupPositionController
   joints:
     - joint1
